// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'logout_response.dart';

/// \[JsonSerializable\] generated code for \[LogoutResponse\].
///
/// This code is generated by the \[JsonSerializable\] package and should not be modified by hand.
/// It includes functions to convert \[LogoutResponse\] instances to and from JSON.
LogoutResponse _$LogoutResponseFromJson(Map<String, dynamic> json) =>
    LogoutResponse(
      success: json['success'] as bool?,
    );

/// Converts a \[LogoutResponse\] instance to a JSON map.
Map<String, dynamic> _$LogoutResponseToJson(LogoutResponse instance) =>
    <String, dynamic>{
      'success': instance.success,
    };