// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'edit_task.dart';

/// \[JsonSerializable\] generated code for \[EditTask\] entity.
///
/// This code is generated by the \[JsonSerializable\] package and should not be modified by hand.
/// It includes functions to convert \[EditTask\] instances to and from JSON.

/// Converts a JSON map to an `EditTask` instance.
///
/// \[param\] json The JSON map to convert.
/// \[return\] An `EditTask` instance.
EditTask _$EditTaskFromJson(Map<String, dynamic> json) => EditTask(
      image: json['image'] as String?,
      title: json['title'] as String?,
      desc: json['desc'] as String?,
      priority: json['priority'] as String?,
      status: json['status'] as String?,
      user: json['auth'] as String?,
    );

/// Converts an `EditTask` instance to a JSON map.
///
/// \[param\] instance The `EditTask` instance to convert.
/// \[return\] A JSON map representing the `EditTask` instance.
Map<String, dynamic> _$EditTaskToJson(EditTask instance) => <String, dynamic>{
      'image': instance.image,
      'title': instance.title,
      'desc': instance.desc,
      'priority': instance.priority,
      'status': instance.status,
      'auth': instance.user,
    };