name: Build and Release APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.2
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build macOS app
        run: flutter build macos --release

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Package macOS app into DMG
        run: |
          create-dmg build/macos/Build/Products/Release/tasky.app \
          build/macos/Build/Products/Release/tasky.dmg

      - name: Create Git tag
        id: tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "::set-output name=tag::$TAG_NAME"
            
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/macos/Build/Products/Release/tasky.app
            build/macos/Build/Products/Release/tasky.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/macos/Build/Products/Release/tasky.app
            build/macos/Build/Products/Release/tasky.dmg
  
