name: Flutter-Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.2
      - uses: oberhauser-dev/flutter-release-action@v0
        with:
          token: ${{ github.token }}
          dry-run: true
          app-name: 'tasky' # Optional, takes the name from pubspec.yaml by default
          app-version: ${{ github.ref_name }} # or set manually: 'v1.2.3-alpha.4', optional, takes the version from pubspec.yaml by default
          tag: ${{ github.ref }}
          build-type: 'debian'
